name: test runner
on: 
 push:
   branches:
     - main  
jobs:
  build:

    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: env
        run: env
        working-directory: /home/jkibari3/first-job




