name: test runner
on: 
 push:
   branches:
     - main  
jobs:
  build:

    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: env
        run: env
        working-directory: /home/jkibari3/first-job




name: hello
on: [push]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
      - name: Say Hello World
        run: echo Hello, world!
